steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/windy-duality-413000/TicTacToe-2:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/windy-duality-413000/TicTacToe-2:$SHORT_SHA']
