steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/windy-duality-413000/github.com/indischeziege/tictactoe-2:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/windy-duality-413000/github.com/indischeziege/tictactoe-2:$SHORT_SHA']
